### ISSUE TITLE
[07/15] Weekly Report

### ISSUE THREAD

**Issue by jiunbae** [jiunbae/Lab#62]
## TODO

- [x] 삼성 첨기연 실습 (07/15)
- [ ] AMANO-RCNN
    - [ ] Frontal-vew detection
    - [ ] Unfold to rectangle and detection
    - [ ] Attach eval metric to callback
- [ ] AMANO-SSD train eval compare

## Objective

Objective
