### ISSUE TITLE
[12/23] Weekly Report

### ISSUE THREAD

**Issue by jiunbae** [jiunbae/Lab#89]
## TODO

- [ ] Amano
    - [ ] Grid classifier (left / center)
    - [ ] Grid classifier backbone mobilenet v2 lite
    - [ ] SSD Backbone mobilenet v2 lite

## Objective

Objective
