### ISSUE TITLE
[01/20] Weekly Report

### ISSUE THREAD

**Issue by jiunbae** [jiunbae/Lab#93]
## TODO

- [ ] Amano
    - [x] Classifier
        - [x] Easy/Hard case separte
        - [x] Crop with padding dataset
    - [ ] Detector
        - [ ] acc report
        - [x] backbone change (mb3, cascade mrcnn)
- [ ] Research
    - [x] self training impl

## Objective

Objective
