### ISSUE TITLE
[02/03] Weekly Report

### ISSUE THREAD

**Issue by jiunbae** [jiunbae/Lab#95]
## TODO

- [ ] Research
    - [ ] SiamVOS from @ hackjinlee
    - [ ] EfficientNet reproduce [github](https://github.com/lukemelas/EfficientNet-PyTorch)
    - [ ] EfficientDet reproduce [github](https://github.com/toandaominh1997/EfficientDet.Pytorch)

## Objective

Objective
