### ISSUE TITLE
[02/10] Weekly Report

### ISSUE THREAD

**Issue by jiunbae** [jiunbae/Lab#96]
## TODO

- [x] Amano
    - [x] 200203 Dataset eval
    - [x] LibTorch Inference speed using EfficientNet
    - [ ] +) Expand to Tracking
- [ ] SiamVOS
    - [x] 학진에게 궁금한 내용 질문
    - [ ] Train, eval reproduce
- [ ] Research
    - [ ] ~~pytorch-ssd original mb2 eval~~
    - [ ] EfficientDet eval
        - [x] VOC
        - [ ] COCO
        - [x] Amano
    - [x] EfficientNet eval
        - [x] Amano
    - [x] ~~Windows LibTorch Inference Speed Issue~~

## Objective

Objective
